-- Migration 001: user_roles
-- Source table: user_roles

CREATE TABLE IF NOT EXISTS user_roles (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT UNSIGNED DEFAULT 1,
    updated_by INT UNSIGNED DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_roles_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
